### ISSUE TITLE
Feature suggestion: DNS for logip

### ISSUE THREAD

**Issue by tkiapril** [exectails/Morrighan#1]
I'm afraid if this is not the right place to ask for a feature, so I apologize if I posted in a wrong place.
The official client works with domain names for logip etc., but Morrighan refuses to accept it.
It would be great if Morrighan can also work with them.

**Comment by exectails** [comment]
This place is fine^^ You're right, Morrighan explicitly checks if logip is a valid IPv4 address. I guess I did that because I didn't know that the client accepts host names. I'll remove the check.

**Comment by exectails** [comment]
https://github.com/exectails/Morrighan/releases/tag/v1.5.8

**Comment by tkiapril** [comment]
:+1:
