### ISSUE TITLE
Minimize Morrighan to System Tray.

### ISSUE THREAD

**Issue by Rietty** [exectails/Morrighan#6]
Since current Morrighan only shows a simple box that is on all the time, it gets a bit annoying when alt tabbing between programs. Is it possible to add a setting, or make it the default behavior for it to minimize it to system tray instead?

**Comment by exectails** [comment]
That would certainly be possible, I might look into it at some point. I think it should be optional and Morrighan should not use the tray icon by default as especially for debugging and solving problems for newcomers it's important to be able to ask "do you see the window", "does it light up on connection", etc.

**Comment by Rietty** [comment]
That would be much appreciated if done. And that does make sense, even as an optional setting, as long as we can enable it and have it persist across sessions.

**Comment by exectails** [comment]
Added in the latest release v1.6.0.

**Comment by Rietty** [comment]
Cheers! Thanks!
