### ISSUE TITLE
Support for G17

### ISSUE THREAD

**Issue by kiairii** [exectails/Morrighan#7]
You added support for g13 I was wondering if you could add support for g17 as well?

**Comment by exectails** [comment]
Actually, I named that argument without G17 in mind, but it should work for it as well. Give it a try.

**Comment by kiairii** [comment]
It does indeed work you should probably rename the argument or make a note about it.
Though I was hoping the pake plugin would work on G17 it seems that it does not.

**Comment by exectails** [comment]
The Pake plugin only works with compatible packet providers, such as Pake+modAlissa or specially tweaked versions of Morrighan, which are private. I'll close this issue (after only half a year, yay!) and make a note in the readme.
