### ISSUE TITLE
NGS

### ISSUE THREAD

**Issue by HakuWasHere** [exectails/Morrighan#9]
After launching via Morrighan I'm getting NGS detected within roughly 3 minutes of opening the game. I've tried with and without utilities that would utilise Morrighan. Is this an issue that you've heard anything about or would you be able to tell me if I'm doing something wrong perhaps?

**Comment by exectails** [comment]
Sorry for not responding sooner, somehow missed this issue. Thanks for the report, I added a new Release a little while ago that NGS shouldn't be detecting yet.

https://github.com/exectails/Morrighan/releases/tag/v1.6.1
